server:
  port: 8081
spring:
  application:
    name: banking-service
  datasource:
    url: jdbc:mariadb://localhost:3306/ONLINE_BANKING_SYSTEM
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: saumyshrey@gmail.com
    password: sucmllywcopxdsbx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    

  