server:
  port: 8081
spring:
  application:
    name: banking-service
  datasource:
    url: jdbc:mariadb://localhost:3306/ONLINE_BANKING_SYSTEM
    username: root
    password: Password@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.ethereal.email
    port: 587
    username: elsie.monahan@ethereal.email
    password: baebPfaxqqybS569kj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    

  